#!/bin/bash

if [ "$1" != "keep" ]; then
  time=_$$_$(date '+%Y-%m-%d_%H_%M')
else
  time=""
fi

log=/root/sagetv_setup_`date '+%Y%m%d_%H%M'`
touch $log

echo "* Verbose log stored at $log..."
dir="sagetv${time}"
buildroot=/usr/local/src/sagetv/
sagedir=/opt/sagetv/server
mkdir -p $sagedir
mkdir -p $buildroot
mkdir -p /var/media
ln -s /recordings /var/media

echo "* Installation some dependencies..."
yum -y --enablerepo=extras install epel-release >> $log 2>&1
rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro >> $log 2>&1
rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm >> $log 2>&1
yum -y install java-1.8.0-openjdk-devel libavc1394-devel libiec61883-devel kernel-devel gcc gcc-c++ zlib-devel freetype-devel libtool automake autoconf yasm vim ffmpeg faad2-libs git perl-IPC-Run perl-Proc-Daemon wget net-tools vim jq comskip >> $log 2>&1
export JDK_HOME=/usr/lib/jvm/java/

echo "* Downloading opensubtitles client..."
git clone https://github.com/emericg/OpenSubtitlesDownload.git /usr/local/sub >> $log 2>&1

# install hdhr service
hdhr_build=/usr/local/src/hdhr
hdhr_dir=/opt/sagetv/hdhomerun
hdhr_cmd=hdhomerun_config
hdhr_file=hdhomerun_config.tgz
mkdir -p $hdhr_build $hdhr_dir
echo "* Setting up prime_encoder for hdhomerun..."
git clone https://github.com/jwittkoski/prime_encoder.git $hdhr_dir >> $log 2>&1
echo "* Downloading hdhr config utility..."
wget http://download.silicondust.com/hdhomerun/libhdhomerun_20180817.tgz -O $hdhr_build/$hdhr_file >> $log 2>&1
cd $hdhr_build
echo "* Unpacking hdhr config utility..."
tar xf $hdhr_file >> $log 2>&1
cd libhdhomerun
echo "* Building hdhr config utility..."
make
cp $hdhr_cmd $hdhr_dir/
device=`$hdhr_dir/$hdhr_cmd discover | awk '{print $3}'`
sed "s/11112222/$device/g" $hdhr_dir/prime_encoder > /tmp/prime.$$
mv -f /tmp/prime.$$ $hdhr_dir/prime_encoder
echo "* Fixing ffmpeg location for prime_encoder..."
ln -s /usr/bin/ffmpeg $hdhr_dir/ffmpeg.2013.09.01

cd $buildroot
echo "* Downloading sagetv..."
git clone https://github.com/google/sagetv.git $dir >> $log 2>&1
cd $dir/build
echo "* Building sagetv..."
./buildall.sh >> $log 2>&1
ls -l $buildroot/$dir/build/sagetv-server*
echo "* creating $sagedir..."
mkdir -p $sagedir
cd $sagedir
echo "* Unpacking sagetv server..."
tar xf $buildroot/$dir/build/sagetv-server*.tar.gz
echo "* Copying config and data backups..."
cp /var/tmp/Wiz.bin $sagedir/
local_ip=`ifconfig  | grep inet\ | awk '{print $2}' | grep -v 127.0.0.1`
sed "s/192.168.1.11/$local_ip/g" /var/tmp/Sage.properties > Sage.properties.new
cp /var/tmp/sdauth $sagedir/
echo "* Unpacking sagetv clients..."
tar xf /var/tmp/clients.tar

for service in prime_encoder sagetv; do 
  echo "* Enabling ${service}..."
  mv -f /var/tmp/${service}.service /usr/lib/systemd/system/
  systemctl enable ${service} >> $log 2>&1
done
