#!/bin/bash

# script to point to look at remaining life on an SSD drive. I added the following 
# line to my .bashrc file:
# echo "SSD life: `cat /etc/lifessd`"

/usr/sbin/smartctl -a /dev/sda | grep Media_Wearout_Indicator |  awk '{print $4}' > /etc/lifessd 2>/dev/null
